const products = [
  {
    id: 1,
    categoryId: 3,
    name: 'Anime #001',
    thumbnail: 'assets/images/products/product-1.png',
    selled: 80,
    price: 12,
  },
  {
    id: 2,
    categoryId: 3,
    name: 'Anime #002',
    thumbnail: 'assets/images/products/product-2.png',
    selled: 17,
    price: 14,
  },
  {
    id: 3,
    categoryId: 3,
    name: 'Anime #003',
    thumbnail: 'assets/images/products/product-3.png',
    selled: 38,
    price: 5,
  },
  {
    id: 4,
    categoryId: 3,
    name: 'Anime #004',
    thumbnail: 'assets/images/products/product-4.png',
    selled: 2,
    price: 8,
  },
  {
    id: 5,
    categoryId: 1,
    name: 'Tượng nghệ thuật',
    thumbnail: 'assets/images/products/product-5.png',
    selled: 8,
    price: 80,
  },
  {
    id: 6,
    categoryId: 5,
    name: 'Animate #001',
    thumbnail: 'assets/images/products/product-6.png',
    selled: 9,
    price: 18,
  },
  {
    id: 7,
    categoryId: 5,
    name: 'Animate #002',
    thumbnail: 'assets/images/products/product-7.png',
    selled: 72,
    price: 22,
  },
  {
    id: 8,
    categoryId: 6,
    name: 'Meta vitural',
    thumbnail: 'assets/images/products/product-8.png',
    selled: 29,
    price: 80,
  },
  {
    id: 9,
    categoryId: 4,
    name: 'Head phone',
    thumbnail: 'assets/images/products/product-9.png',
    selled: 46,
    price: 75,
  },
  {
    id: 10,
    categoryId: 3,
    name: 'Anime #005',
    thumbnail: 'assets/images/products/product-10.png',
    selled: 35,
    price: 30,
  },
  {
    id: 11,
    categoryId: 3,
    name: 'Anime #006',
    thumbnail: 'assets/images/products/product-11.png',
    selled: 17,
    price: 22,
  },
  {
    id: 12,
    categoryId: 3,
    name: 'Anime #007',
    thumbnail: 'assets/images/products/product-12.png',
    selled: 80,
    price: 24,
  },
  {
    id: 13,
    categoryId: 3,
    name: 'Anime #008',
    thumbnail: 'assets/images/products/product-13.png',
    selled: 89,
    price: 24,
  },
];

export default products;
